### ISSUE TITLE
New s390x test failures on Fedora in 0.12.2

### ISSUE THREAD

**Issue by musicinmybrain** [quintusdias/glymur#604] opened 2023-01-07 14:25 UTC
With 0.12.2, we’re [seeing some new failures on s390x](https://src.fedoraproject.org/rpms/python-glymur/pull-request/10) in Fedora Rawhide. I can reproduce these in Fedora 37 as well.

```
=================================== FAILURES ===================================
_______________________ TestSuite.test_rgb_tiled_bigtiff _______________________
self = <tests.test_tiff2jp2.TestSuite testMethod=test_rgb_tiled_bigtiff>
    def test_rgb_tiled_bigtiff(self):
        """
        SCENARIO:  Convert RGB BigTIFF file to JP2.  The TIFF is evenly
        tiled 2x2.

        EXPECTED RESULT:  The data matches.  The JP2 file has 4 tiles.
        """
        with Tiff2Jp2k(
            self.ycbcr_bg, self.temp_jp2_filename, tilesize=(256, 256),
        ) as j:
            j.run()

        jp2 = Jp2k(self.temp_jp2_filename)
        actual = jp2[:]
        expected = skimage.io.imread(self.ycbcr_bg, plugin='pil')
>       np.testing.assert_array_equal(actual, expected)
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 714647 / 786432 (90.9%)
E       Max absolute difference: 255
E       Max relative difference: 255.
E        x: array([[[255, 157, 138],
E               [255, 116,  99],
E               [255,  77,  62],...
E        y: array([[[147, 138, 157],
E               [108,  99, 116],
E               [ 70,  62,  77],...
tests/test_tiff2jp2.py:767: AssertionError
____________________ TestSuite.test_ycbcr_jpeg_single_tile _____________________
self = <tests.test_tiff2jp2.TestSuite testMethod=test_ycbcr_jpeg_single_tile>
    def test_ycbcr_jpeg_single_tile(self):
        """
        SCENARIO:  Convert YCBCR/JPEG TIFF file to JP2.  The TIFF is evenly
        tiled 2x2, but no tilesize is specified.

        EXPECTED RESULT:  The data matches.
        """
        with Tiff2Jp2k(
            self.astronaut_ycbcr_jpeg_tiled, self.temp_jp2_filename
        ) as j:
            j.run()

        jp2 = Jp2k(self.temp_jp2_filename)
        actual = jp2[:]
        expected = skimage.io.imread(
            self.astronaut_ycbcr_jpeg_tiled, plugin='pil'
        )
>       np.testing.assert_array_equal(actual, expected)
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 714647 / 786432 (90.9%)
E       Max absolute difference: 255
E       Max relative difference: 255.
E        x: array([[[255, 157, 138],
E               [255, 116,  99],
E               [255,  77,  62],...
E        y: array([[[147, 138, 157],
E               [108,  99, 116],
E               [ 70,  62,  77],...
tests/test_tiff2jp2.py:867: AssertionError
________________________ TestSuite.test_ycbcr_jpeg_tiff ________________________
self = <tests.test_tiff2jp2.TestSuite testMethod=test_ycbcr_jpeg_tiff>
    def test_ycbcr_jpeg_tiff(self):
        """
        SCENARIO:  Convert YCBCR/JPEG TIFF file to JP2.  The TIFF is evenly
        tiled 2x2.

        EXPECTED RESULT:  The data matches.  The JP2 file has 4 tiles.
        """
        with Tiff2Jp2k(
            self.astronaut_ycbcr_jpeg_tiled, self.temp_jp2_filename,
            tilesize=(256, 256)
        ) as j:
            j.run()

        jp2 = Jp2k(self.temp_jp2_filename)
        actual = jp2[:]
        expected = skimage.io.imread(
            self.astronaut_ycbcr_jpeg_tiled, plugin='pil'
        )
>       np.testing.assert_array_equal(actual, expected)
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 714647 / 786432 (90.9%)
E       Max absolute difference: 255
E       Max relative difference: 255.
E        x: array([[[255, 157, 138],
E               [255, 116,  99],
E               [255,  77,  62],...
E        y: array([[[147, 138, 157],
E               [108,  99, 116],
E               [ 70,  62,  77],...
tests/test_tiff2jp2.py:842: AssertionError
___________________ TestSuite.test_ycbcr_jpeg_unevenly_tiled ___________________
self = <tests.test_tiff2jp2.TestSuite testMethod=test_ycbcr_jpeg_unevenly_tiled>
    def test_ycbcr_jpeg_unevenly_tiled(self):
        """
        SCENARIO:  Convert YCBCR/JPEG TIFF file to JP2.  The TIFF is evenly
        tiled 2x2.  The JPEG 2000 file will be tiled 75x75.

        EXPECTED RESULT:  The data matches.  No errors
        """
        with Tiff2Jp2k(
            self.astronaut_ycbcr_jpeg_tiled, self.temp_jp2_filename,
            tilesize=(75, 75)
        ) as j:
            j.run()

        jp2 = Jp2k(self.temp_jp2_filename)
        actual = jp2[:]
        expected = skimage.io.imread(
            self.astronaut_ycbcr_jpeg_tiled, plugin='pil'
        )
>       np.testing.assert_array_equal(actual, expected)
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 714647 / 786432 (90.9%)
E       Max absolute difference: 255
E       Max relative difference: 255.
E        x: array([[[255, 157, 138],
E               [255, 116,  99],
E               [255,  77,  62],...
E        y: array([[[147, 138, 157],
E               [108,  99, 116],
E               [ 70,  62,  77],...
tests/test_tiff2jp2.py:816: AssertionError
=========================== short test summary info ============================
FAILED tests/test_tiff2jp2.py::TestSuite::test_rgb_tiled_bigtiff - AssertionE...
FAILED tests/test_tiff2jp2.py::TestSuite::test_ycbcr_jpeg_single_tile - Asser...
FAILED tests/test_tiff2jp2.py::TestSuite::test_ycbcr_jpeg_tiff - AssertionErr...
FAILED tests/test_tiff2jp2.py::TestSuite::test_ycbcr_jpeg_unevenly_tiled - As...
================== 4 failed, 578 passed, 5 skipped in 59.74s ===================
```

**Comment by avalentino** [comment] 2023-01-14 16:16
Same issue in debian

**Comment by avalentino** [comment] 2023-01-14 16:24
Probably the issue is related to the fact that s390x is a big-endian architecture

**Comment by sanjayankur31** [comment] 2023-02-13 13:12
Hi folks, any updates/patches here? :)

**Comment by sanjayankur31** [comment] 2023-02-16 10:19
Thanks @quintusdias, no worries---just checking while updating the Fedora package etc.

**Comment by avalentino** [comment] 2023-03-04 07:49
Additional information have been provided in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1032291.

In particular it has been

"verified that the tests from 0.12.1 pass with either the 0.12.1 or
0.12.2 code, and the tests from 0.12.2 fail with either the 0.12.1 or 0.12.2
code"

The full test log is available at the following url: https://ci.debian.net/data/autopkgtest/testing/s390x/g/glymur/30150565/log.gz

**Comment by quintusdias** [comment] 2023-04-29 18:08
So, I'll start off with apologies for not getting on this earlier.  These new failures are coming from the ctypes interface to the libtiff library, it seems the ordering of the image layers (RGBA interface only) is being returned in reverse order.  Seems like something that can be compensated for, but first I'm reviewing the libtiff documentation first in order to see if there isn't something there that I've overlooked.   The other tests involving libtiff seem ok.

**Comment by quintusdias** [comment] 2023-04-29 18:12
and yes, sounds like a big-endian / little-endian issue, but I did some work a lifetime ago using libtiff on big-endian sparc hardware and I don't recall seeing this.

**Comment by quintusdias** [comment] 2023-05-03 22:39
I think we can close this, tests passing on s390x as of commit 08647a558b0a97fa5199a52729c940c8e1b1ad1c

**Closed by quintusdias** 2023-05-03 22:39 UTC

**Comment by musicinmybrain** [comment] 2023-05-04 00:02
I’ll wait for a release to actually update the Fedora package, but I can confirm that a [test build](https://koji.fedoraproject.org/koji/taskinfo?taskID=100705664) using a snapshot from https://github.com/quintusdias/glymur/commit/08647a558b0a97fa5199a52729c940c8e1b1ad1c seems to work as expected on `s390x` (and everywhere else).
